from pymongo import MongoClient
import pymongo
import bcrypt

# Create a new connection to the polylink database
con = MongoClient("mongodb://localhost:27017")
db = con["polylink"]

# Let's define some utilities functions
def register(firstname, lastname, username, password):
    """ This handles a new user registration. It returns nothing"""
    db.users.insert_one({
        "first_name": firstname,
        "last_name": lastname,
        "username": username,
        "password": bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8"),
    })
    return

def login(username, password):
    """ Handles user login. It creates a new session and returns its id if successful or returns None otherwise."""
    user = db.users.find_one({"username": username})
    if user: 
        if bcrypt.checkpw(password.encode("utf-8"), user["password"].encode("utf-8")):  # check if password matches
            # Create a new session
            session = db.sessions.insert_one({})  # generate it first to have a _id generated by MongoDB
            session_id = str(session.inserted_id)
            db.sessions.update_one(             # take that _id, stringuy it and use it as a session_id
                {"_id": session.inserted_id},
                {"$set": {
                    "session_id": session_id,
                    "user_id": user["_id"],
                    }
                },
            )

            return session_id
    return None

def change_password(username, old_password, new_password):
    """ Handles password changes for users. Returns true if succesful, fasle otherwise."""
    user = db.users.find_one({"username": username})
    if user: 
        if bcrypt.checkpw(old_password.encode("utf-8"), user["password"].encode("utf-8")):  # check if password matches
            db.users.update_one(
                {"username": user["username"]}, 
                {
                    "$set": {"password": bcrypt.hashpw(new_password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")}
                }
            )
            return True
    return False

def get_user_by_session_id(session_id):
    """ This retrieve a user from the database using a session id."""
    user_id = db.sessions.find_one({"session_id": session_id})["user_id"]
    user = db.users.find_one({"_id": user_id})
    return dict(user)

def remove_session(session_id):
    """ Handles sessions deletion. It returns true if succesful"""
    session = db.sessions.delete_one({"session_id": session_id})
    return bool(session)
    
def isUsername(username):
    return bool(db.users.find_one({"username": username}))

# register("minato", "shee", "minatoshee", "nice")

# print(f"{type(login("matarfaly", "nico")["_id"]) == "68222f88350ff534dd6c4bd0"}")
# print(login("matarfaly", "nico"))