from pymongo import MongoClient
import pymongo
import bcrypt
from bson import Binary, ObjectId
from django.http import HttpRequest
from datetime import datetime, timezone

# Create a new connection to the polylink database
con = MongoClient("mongodb://localhost:27017")
db = con["polylink"]

# Let's define some utilities functions
def register(firstname, lastname, username, password):
    """ This handles a new user registration. It returns nothing"""
    db.users.insert_one({
        "first_name": firstname,
        "last_name": lastname,
        "username": username,
        "password": bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8"),
    })
    return

def login(username, password):
    """ Handles user login. It creates a new session and returns its id if successful or returns None otherwise."""
    user = db.users.find_one({"username": username})
    if user: 
        if bcrypt.checkpw(password.encode("utf-8"), user["password"].encode("utf-8")):  # check if password matches
            # Create a new session
            session = db.sessions.insert_one({})  # generate it first to have a _id generated by MongoDB
            session_id = str(session.inserted_id)
            db.sessions.update_one(             # take that _id, stringuy it and use it as a session_id
                {"_id": session.inserted_id},
                {"$set": {
                    "session_id": session_id,
                    "user_id": user["_id"],
                    }
                },
            )

            return session_id
    return None

def change_password(username, old_password, new_password):
    """ Handles password changes for users. Returns true if succesful, fasle otherwise."""
    user = db.users.find_one({"username": username})
    if user: 
        if bcrypt.checkpw(old_password.encode("utf-8"), user["password"].encode("utf-8")):  # check if password matches
            db.users.update_one(
                {"username": user["username"]}, 
                {
                    "$set": {"password": bcrypt.hashpw(new_password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")}
                }
            )
            return True
    return False

def get_user_by_session_id(session_id):
    """ This retrieve a user from the database using a session id. I returns a dictionny containing information about the user."""
    user_id = db.sessions.find_one({"session_id": session_id})["user_id"]
    user = db.users.find_one({"_id": user_id})
    return user

def get_user(request: HttpRequest):
    """ This retrieve a user from the database using a session id. The retrieve the session id from the receive request object.
        It returns a dictionny containing information about the user. """
    session_id = request.COOKIES.get("session_id", None)
    if not session_id:
        return None
    return get_user_by_session_id(session_id)

def get_user_id_by_session_id(session_id):
    """ This retrieves a user'id from the database using a session id. It returns the id in a string representation """
    user_id = db.sessions.find_one({"session_id": session_id})["user_id"]
    if not user_id:
        return None
    return user_id

def get_user_id(request: HttpRequest):
    """ This retrieve a user from the database using a session id. The retrieve the session id from the receive request object.
    It returns a dictionny containing information about the user. """
    return get_user_id_by_session_id(request.COOKIES.get("session_id", None))


def remove_session(session_id):
    """ Handles sessions deletion. It returns true if succesful"""
    session = db.sessions.delete_one({"session_id": session_id})
    return bool(session)
    
def isUsername(username):
    return bool(db.users.find_one({"username": username}))

##### utily function for testing purpose only
def output_dict(dic):
    print("{")
    for key, value in dic.items():
        print(f"{key}: {value}")
    print("}")

# with open("100 men 1 gorilla.mp4", "rb") as file:
#     vid_byes = file.read()
#     format = "mp4"

# with open("thumbnail.png", "rb") as file:
#     thumbnail = file.read()
#     th_format = "png"

# db.stories.insert_one({
#     "author": ObjectId("68222f88350ff534dd6c4bd0"),
#     "views": 0,
#     "likes": 0,
#     "format": format,
#     "thumnail_format": th_format,
#     "date": datetime.now(timezone.utc),
#     "content": Binary(vid_byes),
#     "thumbnail": Binary(thumbnail),
# })


# pipeline = [
#                 {"$match": {"author": ObjectId("68222f88350ff534dd6c4bd0")}},
#                 {"$project": {"_id":1}},
#             ]

# st = db.stories.aggregate(pipeline)

# pipeline = [
#                 {"$match": {"author": ObjectId("68222f88350ff534dd6c4bd0")}},
#                 {"$project": {"_id": 1, "id": "$_id"}},
#             ]
# stories = db.stories.aggregate(pipeline) # We will need an iterable in the template
# print('==========')
# for s in stories:
#     print(s)
# print('==========')
